export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";
export const FETCH_DATA_FULFILLED = "FETCH_DATA_FULFILLED";
export const FETCH_DATA_REJECTED = "FETCH_DATA_REJECTED";



export const FETCH_SECONDARYDATA_PENDING = "FETCH_SECONDARYDATA_PENDING";
export const FETCH_SECONDARYDATA_FULFILLED = "FETCH_SECONDARYDATA_FULFILLED";
export const FETCH_SECONDARYDATA_REJECTED = "FETCH_SECONDARYDATA_REJECTED";





export const FETCH_DATAFAST_PENDING = "FETCH_DATAFAST_PENDING";
export const FETCH_DATAFAST_FULFILLED = "FETCH_DATAFAST_FULFILLED";
export const FETCH_DATAFAST_REJECTED = "FETCH_DATAFAST_REJECTED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER= "DELETE_CUSTOMER";

export const FETCH_SPENDITEMS_PENDING = "FETCH_SPENDITEMS_PENDING";
export const FETCH_SPENDITEMS_FULFILLED = "FETCH_SPENDITEMS_FULFILLED";
export const FETCH_SPENDITEMS_REJECTED = "FETCH_SPENDITEMS_REJECTED";

export const FETCH_DATA_EDIT_PENDING = "FETCH_DATA_EDIT_PENDING";
export const FETCH_DATA_EDIT_FULFILLED = "FETCH_DATA_EDIT_FULFILLED";
export const FETCH_DATA_EDIT_REJECTED = "FETCH_DATA_EDIT_REJECTED";

export const PUT_DATA_PENDING = "PUT_DATA_PENDING";
export const PUT_DATA_FULFILLED = "PUT_DATA_FULFILLED";
export const PUT_DATA_REJECTED = "PUT_DATA_REJECTED";




export const FETCH_MENU_PENDING = "FETCH_MENU_PENDING";
export const FETCH_MENU_FULFILLED = "FETCH_MENU_FULFILLED";
export const FETCH_MENU_REJECTED = "FETCH_MENU_REJECTED";


export const FETCH_DASHBOARD_PENDING = "FETCH_DASHBOARD_PENDING";
export const FETCH_DASHBOARD_FULFILLED = "FETCH_DASHBOARD_FULFILLED";
export const FETCH_DASHBOARD_REJECTED = "FETCH_DASHBOARD_REJECTED";


export const FETCH_SETTINGS_PENDING = "FETCH_SETTINGS_PENDING";
export const FETCH_SETTINGS_FULFILLED = "FETCH_SETTINGS_FULFILLED";
export const FETCH_SETTINGS_REJECTED = "FETCH_SETTINGS_REJECTED";


export const FETCH_UPDATE_SETTINGS_PENDING = "FETCH_UPDATE_SETTINGS_PENDING";
export const FETCH_UPDATE_SETTINGS_FULFILLED = "FETCH_UPDATE_SETTINGS_FULFILLED";
export const FETCH_UPDATE_SETTINGS_REJECTED = "FETCH_UPDATE_SETTINGS_REJECTED";


export const FETCH_REFLIST_FULFILLED = "FETCH_REFLIST_FULFILLED";
export const FETCH_REFLIST_REJECTED = "FETCH_REFLIST_REJECTED";
export const FETCH_REFLIST_PENDING = "FETCH_REFLIST_PENDING";

export const FETCH_ATTRIBUTES_FULFILLED = "FETCH_ATTRIBUTES_FULFILLED";
export const FETCH_ATTRIBUTES_PENDING = "FETCH_ATTRIBUTES_PENDING";
export const FETCH_ATTRIBUTES_REJECTED = "FETCH_ATTRIBUTES_REJECTED";




export const FETCH_GROUPS_PENDING = "FETCH_GROUPS_PENDING";
export const FETCH_GROUPS_FULFILLED = "FETCH_GROUPS_FULFILLED";
export const FETCH_GROUPS_REJECTED = "FETCH_GROUPS_REJECTED";


export const FETCH_OWNERS_PENDING = "FETCH_OWNERS_PENDING";
export const FETCH_OWNERS_FULFILLED = "FETCH_OWNERS_FULFILLED";
export const FETCH_OWNERS_REJECTED = "FETCH_OWNERS_REJECTED";



export const FETCH_DEPARTMENTS_PENDING = "FETCH_DEPARTMENTS_PENDING";
export const FETCH_DEPARTMENTS_FULFILLED = "FETCH_DEPARTMENTS_FULFILLED";
export const FETCH_DEPARTMENTS_REJECTED = "FETCH_DEPARTMENTS_REJECTED";

export const FETCH_FAST_GROUPS_PENDING = "FETCH_FAST_GROUPS_PENDING";
export const FETCH_FAST_GROUPS_FULFILLED = "FETCH_FAST_GROUPS_FULFILLED";
export const FETCH_FAST_GROUPS_REJECTED = "FETCH_FAST_GROUPS_REJECTED";



export const FETCH_CUSTOMERS_FAST_PENDING = "FETCH_CUSTOMERS_FAST_PENDING";
export const FETCH_CUSTOMERS_FAST_FULFILLED = "FETCH_CUSTOMERS_FAST_FULFILLED";
export const FETCH_CUSTOMERS_FAST_REJECTED = "FETCH_CUSTOMERS_FAST_REJECTED";


export const FETCH_CUSTOMERS_PENDING = "FETCH_CUSTOMERS_PENDING";
export const FETCH_CUSTOMERS_FULFILLED = "FETCH_CUSTOMERS_FULFILLED";
export const FETCH_CUSTOMERS_REJECTED = "FETCH_CUSTOMERS_REJECTED";

export const FETCH_BARCODE_PENDING = "FETCH_BARCODE_PENDING";
export const FETCH_BARCODE_FULFILLED = "FETCH_BARCODE_FULFILLED";
export const FETCH_BARCODE_REJECTED = "FETCH_BARCODE_REJECTED";
export const DELETE_BARCODE = "DELETE_BARCODE";

export const FETCH_CARD_PENDING = "FETCH_CARD_PENDING";
export const FETCH_CARD_FULFILLED = "FETCH_CARD_FULFILLED";
export const FETCH_CARD_REJECTED = "FETCH_CARD_REJECTED";


export const FETCH_MARK_PENDING = "FETCH_MARK_PENDING";
export const FETCH_MARK_FULFILLED = "FETCH_MARK_FULFILLED";
export const FETCH_MARK_REJECTED = "FETCH_MARK_REJECTED";


export const FETCH_LINKS_PENDING = "FETCH_LINKS_PENDING";
export const FETCH_LINKS_FULFILLED = "FETCH_LINKS_FULFILLED";
export const FETCH_LINKS_REJECTED = "FETCH_LINKS_REJECTED";



//fETCHING EXPORTS FOR DOC MODAL STARTS HERE
export const FETCH_CUSTOMER_GROUPS_MODAL_PENDING = "FETCH_CUSTOMER_GROUPS_MODAL_PENDING";
export const FETCH_CUSTOMER_GROUPS_MODAL_FULFILLED = "FETCH_CUSTOMER_GROUPS_MODAL_FULFILLED";
export const FETCH_CUSTOMER_GROUPS_MODAL_REJECTED = "FETCH_CUSTOMER_GROUPS_MODAL_REJECTED";


export const FETCH_STOCKS_GROUPS_MODAL_PENDING = "FETCH_STOCKS_GROUPS_MODAL_PENDING";
export const FETCH_STOCKS_GROUPS_MODAL_FULFILLED = "FETCH_STOCKS_GROUPS_MODAL_FULFILLED";
export const FETCH_STOCKS_GROUPS_MODAL_REJECTED = "FETCH_STOCKS_GROUPS_MODAL_REJECTED";



export const PUT_DATA_CUSTOMER_PENDING = "PUT_DATA_CUSTOMER_PENDING";
export const PUT_DATA_CUSTOMER_FULFILLED = "PUT_DATA_CUSTOMER_FULFILLED";
export const PUT_DATA_CUSTOMER_REJECTED = "PUT_DATA_CUSTOMER_REJECTED";


export const PUT_DATA_STOCK_PENDING = "PUT_DATA_STOCK_PENDING";
export const PUT_DATA_STOCK_FULFILLED = "PUT_DATA_STOCK_FULFILLED";
export const PUT_DATA_STOCK_REJECTED = "PUT_DATA_STOCK_REJECTED";


export const PUT_DATA_PRODUCT_PENDING = "PUT_DATA_PRODUCT_PENDING";
export const PUT_DATA_PRODUCT_FULFILLED = "PUT_DATA_PRODUCT_FULFILLED";
export const PUT_DATA_PRODUCT_REJECTED = "PUT_DATA_PRODUCT_REJECTED";




export const FETCH_PRODUCTS_MODAL_PENDING = "FETCH_PRODUCTS_MODAL_PENDING";
export const FETCH_PRODUCTS_MODAL_FULFILLED = "FETCH_PRODUCTS_MODAL_FULFILLED";
export const FETCH_PRODUCTS_MODAL_REJECTED = "FETCH_PRODUCTS_MODAL_REJECTED";

export const FETCH_PRODUCTS_GROUP_MODAL_PENDING = "FETCH_PRODUCTS_GROUP_MODAL_PENDING";
export const FETCH_PRODUCTS_GROUP_MODAL_FULFILLED = "FETCH_PRODUCTS_GROUP_MODAL_FULFILLED";
export const FETCH_PRODUCTS_GROUP_MODAL_REJECTED = "FETCH_PRODUCTS_GROUP_MODAL_REJECTED";



//FETCHING EXPORT FOR DOC MODAL ENDS HERE

export const initialState = {
    fetching: false,
    datas: [],
    headerDatas: [],
    error: {},
    columns: [],
    navbar:[],
    groups:[],
    colnames:[],
    price:0,
    marks:[],
    links:[],
    markLoading:false,
    linkLoading:false,
    lang:'eng'
};
